# Generated by Django 4.2.7 on 2024-08-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebox',
            name='descriptions',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='imagebox',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
